language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - composer self-update
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush
 - phpenv rehash
 - mkdir private
 - mkdir tmp
 - cd drupal
 - drush si custom --db-url=mysql://root:@localhost/drupal --yes install_configure_form.update_status_module='array(FALSE,FALSE)'
 - drush en site_deployment -y
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - cd ..
 - composer --no-progress install

script:
  - bin/behat -c travis.behat.yml
